# TCL File Generated by Component Editor 16.1
# Sat Jul 19 11:24:18 EST 2025
# DO NOT MODIFY


# 
# framebuffer_writer "framebuffer_writer" v1.0
#  2025.07.19.11:24:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module framebuffer_writer
# 
set_module_property DESCRIPTION ""
set_module_property NAME framebuffer_writer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Private IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME framebuffer_writer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL framebuffer_writer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file framebuffer_writer.sv SYSTEM_VERILOG PATH framebuffer_writer.sv TOP_LEVEL_FILE
add_fileset_file graphics_pkg.sv SYSTEM_VERILOG PATH graphics_pkg.sv
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH ../vga/vga_pkg.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL framebuffer_writer
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file framebuffer_writer.sv SYSTEM_VERILOG PATH framebuffer_writer.sv
add_fileset_file graphics_pkg.sv SYSTEM_VERILOG PATH graphics_pkg.sv
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH ../vga/vga_pkg.sv


# 
# parameters
# 
add_parameter MM_START_ADDRESS INTEGER 0
set_parameter_property MM_START_ADDRESS DEFAULT_VALUE 0
set_parameter_property MM_START_ADDRESS DISPLAY_NAME MM_START_ADDRESS
set_parameter_property MM_START_ADDRESS TYPE INTEGER
set_parameter_property MM_START_ADDRESS UNITS None
set_parameter_property MM_START_ADDRESS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_START_ADDRESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm_master_memory
# 
add_interface mm_master_memory avalon start
set_interface_property mm_master_memory addressUnits SYMBOLS
set_interface_property mm_master_memory associatedClock clock
set_interface_property mm_master_memory associatedReset reset
set_interface_property mm_master_memory bitsPerSymbol 8
set_interface_property mm_master_memory burstOnBurstBoundariesOnly false
set_interface_property mm_master_memory burstcountUnits WORDS
set_interface_property mm_master_memory doStreamReads false
set_interface_property mm_master_memory doStreamWrites false
set_interface_property mm_master_memory holdTime 0
set_interface_property mm_master_memory linewrapBursts false
set_interface_property mm_master_memory maximumPendingReadTransactions 0
set_interface_property mm_master_memory maximumPendingWriteTransactions 0
set_interface_property mm_master_memory readLatency 0
set_interface_property mm_master_memory readWaitTime 1
set_interface_property mm_master_memory setupTime 0
set_interface_property mm_master_memory timingUnits Cycles
set_interface_property mm_master_memory writeWaitTime 0
set_interface_property mm_master_memory ENABLED true
set_interface_property mm_master_memory EXPORT_OF ""
set_interface_property mm_master_memory PORT_NAME_MAP ""
set_interface_property mm_master_memory CMSIS_SVD_VARIABLES ""
set_interface_property mm_master_memory SVD_ADDRESS_GROUP ""

add_interface_port mm_master_memory mm_write write Output 1
add_interface_port mm_master_memory mm_address address Output 32
add_interface_port mm_master_memory mm_writedata writedata Output 16
add_interface_port mm_master_memory mm_waitrequest waitrequest Input 1


# 
# connection point pixel_sink
# 
add_interface pixel_sink avalon_streaming end
set_interface_property pixel_sink associatedClock clock
set_interface_property pixel_sink associatedReset reset
set_interface_property pixel_sink dataBitsPerSymbol 8
set_interface_property pixel_sink errorDescriptor ""
set_interface_property pixel_sink firstSymbolInHighOrderBits true
set_interface_property pixel_sink maxChannel 255
set_interface_property pixel_sink readyLatency 0
set_interface_property pixel_sink ENABLED true
set_interface_property pixel_sink EXPORT_OF ""
set_interface_property pixel_sink PORT_NAME_MAP ""
set_interface_property pixel_sink CMSIS_SVD_VARIABLES ""
set_interface_property pixel_sink SVD_ADDRESS_GROUP ""

add_interface_port pixel_sink st_ready ready Output 1
add_interface_port pixel_sink st_valid valid Input 1
add_interface_port pixel_sink st_data data Input 48
add_interface_port pixel_sink st_channel channel Input 8

