# TCL File Generated by Component Editor 20.1
# Mon Aug 18 16:38:18 AEST 2025
# DO NOT MODIFY


# 
# graphics_line "graphics_line" v1.0
#  2025.08.18.16:38:18
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module graphics_line
# 
set_module_property DESCRIPTION ""
set_module_property NAME graphics_line
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Private IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME graphics_line
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL graphics_line
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file graphics_line.sv SYSTEM_VERILOG PATH graphics_line.sv TOP_LEVEL_FILE
add_fileset_file graphics_pkg.sv SYSTEM_VERILOG PATH graphics_pkg.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL graphics_line
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file graphics_line.sv SYSTEM_VERILOG PATH graphics_line.sv
add_fileset_file graphics_pkg.sv SYSTEM_VERILOG PATH graphics_pkg.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm_slave_csr
# 
add_interface mm_slave_csr avalon end
set_interface_property mm_slave_csr addressUnits WORDS
set_interface_property mm_slave_csr associatedClock clock
set_interface_property mm_slave_csr associatedReset reset
set_interface_property mm_slave_csr bitsPerSymbol 8
set_interface_property mm_slave_csr burstOnBurstBoundariesOnly false
set_interface_property mm_slave_csr burstcountUnits WORDS
set_interface_property mm_slave_csr explicitAddressSpan 0
set_interface_property mm_slave_csr holdTime 0
set_interface_property mm_slave_csr linewrapBursts false
set_interface_property mm_slave_csr maximumPendingReadTransactions 0
set_interface_property mm_slave_csr maximumPendingWriteTransactions 0
set_interface_property mm_slave_csr readLatency 0
set_interface_property mm_slave_csr readWaitTime 1
set_interface_property mm_slave_csr setupTime 0
set_interface_property mm_slave_csr timingUnits Cycles
set_interface_property mm_slave_csr writeWaitTime 0
set_interface_property mm_slave_csr ENABLED true
set_interface_property mm_slave_csr EXPORT_OF ""
set_interface_property mm_slave_csr PORT_NAME_MAP ""
set_interface_property mm_slave_csr CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave_csr SVD_ADDRESS_GROUP ""

add_interface_port mm_slave_csr mm_csr_write write Input 1
add_interface_port mm_slave_csr mm_csr_address address Input 4
add_interface_port mm_slave_csr mm_csr_writedata writedata Input 32
add_interface_port mm_slave_csr mm_csr_waitrequest waitrequest Output 1
set_interface_assignment mm_slave_csr embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point pixel_source
# 
add_interface pixel_source avalon_streaming start
set_interface_property pixel_source associatedClock clock
set_interface_property pixel_source associatedReset reset
set_interface_property pixel_source dataBitsPerSymbol 8
set_interface_property pixel_source errorDescriptor ""
set_interface_property pixel_source firstSymbolInHighOrderBits true
set_interface_property pixel_source maxChannel 0
set_interface_property pixel_source readyLatency 0
set_interface_property pixel_source ENABLED true
set_interface_property pixel_source EXPORT_OF ""
set_interface_property pixel_source PORT_NAME_MAP ""
set_interface_property pixel_source CMSIS_SVD_VARIABLES ""
set_interface_property pixel_source SVD_ADDRESS_GROUP ""

add_interface_port pixel_source st_ready ready Input 1
add_interface_port pixel_source st_data data Output 48
add_interface_port pixel_source st_valid valid Output 1


# 
# connection point op_ctrl
# 
add_interface op_ctrl conduit end
set_interface_property op_ctrl associatedClock clock
set_interface_property op_ctrl associatedReset reset
set_interface_property op_ctrl ENABLED true
set_interface_property op_ctrl EXPORT_OF ""
set_interface_property op_ctrl PORT_NAME_MAP ""
set_interface_property op_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property op_ctrl SVD_ADDRESS_GROUP ""

add_interface_port op_ctrl start start Input 1
add_interface_port op_ctrl done done Output 1
add_interface_port op_ctrl clken clken Input 1

