# TCL File Generated by Component Editor 20.1
# Fri Aug 15 19:04:36 AEST 2025
# DO NOT MODIFY


# 
# vga_frame_buffer_mux "vga_frame_buffer_mux" v1.0
#  2025.08.15.19:04:36
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_frame_buffer_mux
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_frame_buffer_mux
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Private IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_frame_buffer_mux
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_frame_buffer_mux
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_frame_buffer_mux.sv SYSTEM_VERILOG PATH vga_frame_buffer_mux.sv TOP_LEVEL_FILE
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH vga_pkg.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_frame_buffer_mux
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_frame_buffer_mux.sv SYSTEM_VERILOG PATH vga_frame_buffer_mux.sv
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH vga_pkg.sv


# 
# parameters
# 
add_parameter MM_CSR_ADDRESS_SOURCE0 INTEGER 0
set_parameter_property MM_CSR_ADDRESS_SOURCE0 DEFAULT_VALUE 0
set_parameter_property MM_CSR_ADDRESS_SOURCE0 DISPLAY_NAME MM_CSR_ADDRESS_SOURCE0
set_parameter_property MM_CSR_ADDRESS_SOURCE0 TYPE INTEGER
set_parameter_property MM_CSR_ADDRESS_SOURCE0 UNITS None
set_parameter_property MM_CSR_ADDRESS_SOURCE0 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_CSR_ADDRESS_SOURCE0 HDL_PARAMETER true
add_parameter MM_CSR_ADDRESS_SOURCE1 INTEGER 0
set_parameter_property MM_CSR_ADDRESS_SOURCE1 DEFAULT_VALUE 0
set_parameter_property MM_CSR_ADDRESS_SOURCE1 DISPLAY_NAME MM_CSR_ADDRESS_SOURCE1
set_parameter_property MM_CSR_ADDRESS_SOURCE1 TYPE INTEGER
set_parameter_property MM_CSR_ADDRESS_SOURCE1 UNITS None
set_parameter_property MM_CSR_ADDRESS_SOURCE1 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_CSR_ADDRESS_SOURCE1 HDL_PARAMETER true
add_parameter MM_CSR_ADDRESS_SOURCE2 INTEGER 0
set_parameter_property MM_CSR_ADDRESS_SOURCE2 DEFAULT_VALUE 0
set_parameter_property MM_CSR_ADDRESS_SOURCE2 DISPLAY_NAME MM_CSR_ADDRESS_SOURCE2
set_parameter_property MM_CSR_ADDRESS_SOURCE2 TYPE INTEGER
set_parameter_property MM_CSR_ADDRESS_SOURCE2 UNITS None
set_parameter_property MM_CSR_ADDRESS_SOURCE2 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_CSR_ADDRESS_SOURCE2 HDL_PARAMETER true
add_parameter MM_CSR_ADDRESS_SOURCE3 INTEGER 0
set_parameter_property MM_CSR_ADDRESS_SOURCE3 DEFAULT_VALUE 0
set_parameter_property MM_CSR_ADDRESS_SOURCE3 DISPLAY_NAME MM_CSR_ADDRESS_SOURCE3
set_parameter_property MM_CSR_ADDRESS_SOURCE3 TYPE INTEGER
set_parameter_property MM_CSR_ADDRESS_SOURCE3 UNITS None
set_parameter_property MM_CSR_ADDRESS_SOURCE3 ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_CSR_ADDRESS_SOURCE3 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm_slave_csr
# 
add_interface mm_slave_csr avalon end
set_interface_property mm_slave_csr addressUnits WORDS
set_interface_property mm_slave_csr associatedClock clock
set_interface_property mm_slave_csr associatedReset reset
set_interface_property mm_slave_csr bitsPerSymbol 8
set_interface_property mm_slave_csr burstOnBurstBoundariesOnly false
set_interface_property mm_slave_csr burstcountUnits WORDS
set_interface_property mm_slave_csr explicitAddressSpan 0
set_interface_property mm_slave_csr holdTime 0
set_interface_property mm_slave_csr linewrapBursts false
set_interface_property mm_slave_csr maximumPendingReadTransactions 0
set_interface_property mm_slave_csr maximumPendingWriteTransactions 0
set_interface_property mm_slave_csr readLatency 0
set_interface_property mm_slave_csr readWaitTime 1
set_interface_property mm_slave_csr setupTime 0
set_interface_property mm_slave_csr timingUnits Cycles
set_interface_property mm_slave_csr writeWaitTime 0
set_interface_property mm_slave_csr ENABLED true
set_interface_property mm_slave_csr EXPORT_OF ""
set_interface_property mm_slave_csr PORT_NAME_MAP ""
set_interface_property mm_slave_csr CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave_csr SVD_ADDRESS_GROUP ""

add_interface_port mm_slave_csr mm_slave_csr_address address Input 4
add_interface_port mm_slave_csr mm_slave_csr_write write Input 1
add_interface_port mm_slave_csr mm_slave_csr_writedata writedata Input 32
add_interface_port mm_slave_csr mm_slave_csr_waitrequest waitrequest Output 1
set_interface_assignment mm_slave_csr embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point mm_master_csr
# 
add_interface mm_master_csr avalon start
set_interface_property mm_master_csr addressUnits SYMBOLS
set_interface_property mm_master_csr associatedClock clock
set_interface_property mm_master_csr associatedReset reset
set_interface_property mm_master_csr bitsPerSymbol 8
set_interface_property mm_master_csr burstOnBurstBoundariesOnly false
set_interface_property mm_master_csr burstcountUnits WORDS
set_interface_property mm_master_csr doStreamReads false
set_interface_property mm_master_csr doStreamWrites false
set_interface_property mm_master_csr holdTime 0
set_interface_property mm_master_csr linewrapBursts false
set_interface_property mm_master_csr maximumPendingReadTransactions 0
set_interface_property mm_master_csr maximumPendingWriteTransactions 0
set_interface_property mm_master_csr readLatency 0
set_interface_property mm_master_csr readWaitTime 1
set_interface_property mm_master_csr setupTime 0
set_interface_property mm_master_csr timingUnits Cycles
set_interface_property mm_master_csr writeWaitTime 0
set_interface_property mm_master_csr ENABLED true
set_interface_property mm_master_csr EXPORT_OF ""
set_interface_property mm_master_csr PORT_NAME_MAP ""
set_interface_property mm_master_csr CMSIS_SVD_VARIABLES ""
set_interface_property mm_master_csr SVD_ADDRESS_GROUP ""

add_interface_port mm_master_csr mm_master_csr_address address Output 32
add_interface_port mm_master_csr mm_master_csr_write write Output 1
add_interface_port mm_master_csr mm_master_csr_writedata writedata Output 32
add_interface_port mm_master_csr mm_master_csr_waitrequest waitrequest Input 1


# 
# connection point st_source
# 
add_interface st_source avalon_streaming start
set_interface_property st_source associatedClock clock
set_interface_property st_source associatedReset reset
set_interface_property st_source dataBitsPerSymbol 8
set_interface_property st_source errorDescriptor ""
set_interface_property st_source firstSymbolInHighOrderBits true
set_interface_property st_source maxChannel 0
set_interface_property st_source readyLatency 0
set_interface_property st_source ENABLED true
set_interface_property st_source EXPORT_OF ""
set_interface_property st_source PORT_NAME_MAP ""
set_interface_property st_source CMSIS_SVD_VARIABLES ""
set_interface_property st_source SVD_ADDRESS_GROUP ""

add_interface_port st_source st_source_data data Output 16
add_interface_port st_source st_source_endofpacket endofpacket Output 1
add_interface_port st_source st_source_startofpacket startofpacket Output 1
add_interface_port st_source st_source_valid valid Output 1
add_interface_port st_source st_source_ready ready Input 1
add_interface_port st_source st_source_empty empty Output 2


# 
# connection point st_sink0
# 
add_interface st_sink0 avalon_streaming end
set_interface_property st_sink0 associatedClock clock
set_interface_property st_sink0 associatedReset reset
set_interface_property st_sink0 dataBitsPerSymbol 8
set_interface_property st_sink0 errorDescriptor ""
set_interface_property st_sink0 firstSymbolInHighOrderBits true
set_interface_property st_sink0 maxChannel 0
set_interface_property st_sink0 readyLatency 0
set_interface_property st_sink0 ENABLED true
set_interface_property st_sink0 EXPORT_OF ""
set_interface_property st_sink0 PORT_NAME_MAP ""
set_interface_property st_sink0 CMSIS_SVD_VARIABLES ""
set_interface_property st_sink0 SVD_ADDRESS_GROUP ""

add_interface_port st_sink0 st_sink0_data data Input 16
add_interface_port st_sink0 st_sink0_empty empty Input 2
add_interface_port st_sink0 st_sink0_endofpacket endofpacket Input 1
add_interface_port st_sink0 st_sink0_startofpacket startofpacket Input 1
add_interface_port st_sink0 st_sink0_ready ready Output 1
add_interface_port st_sink0 st_sink0_valid valid Input 1


# 
# connection point st_sink1
# 
add_interface st_sink1 avalon_streaming end
set_interface_property st_sink1 associatedClock clock
set_interface_property st_sink1 associatedReset reset
set_interface_property st_sink1 dataBitsPerSymbol 8
set_interface_property st_sink1 errorDescriptor ""
set_interface_property st_sink1 firstSymbolInHighOrderBits true
set_interface_property st_sink1 maxChannel 0
set_interface_property st_sink1 readyLatency 0
set_interface_property st_sink1 ENABLED true
set_interface_property st_sink1 EXPORT_OF ""
set_interface_property st_sink1 PORT_NAME_MAP ""
set_interface_property st_sink1 CMSIS_SVD_VARIABLES ""
set_interface_property st_sink1 SVD_ADDRESS_GROUP ""

add_interface_port st_sink1 st_sink1_data data Input 16
add_interface_port st_sink1 st_sink1_empty empty Input 2
add_interface_port st_sink1 st_sink1_endofpacket endofpacket Input 1
add_interface_port st_sink1 st_sink1_startofpacket startofpacket Input 1
add_interface_port st_sink1 st_sink1_ready ready Output 1
add_interface_port st_sink1 st_sink1_valid valid Input 1


# 
# connection point st_sink2
# 
add_interface st_sink2 avalon_streaming end
set_interface_property st_sink2 associatedClock clock
set_interface_property st_sink2 associatedReset reset
set_interface_property st_sink2 dataBitsPerSymbol 8
set_interface_property st_sink2 errorDescriptor ""
set_interface_property st_sink2 firstSymbolInHighOrderBits true
set_interface_property st_sink2 maxChannel 0
set_interface_property st_sink2 readyLatency 0
set_interface_property st_sink2 ENABLED true
set_interface_property st_sink2 EXPORT_OF ""
set_interface_property st_sink2 PORT_NAME_MAP ""
set_interface_property st_sink2 CMSIS_SVD_VARIABLES ""
set_interface_property st_sink2 SVD_ADDRESS_GROUP ""

add_interface_port st_sink2 st_sink2_data data Input 16
add_interface_port st_sink2 st_sink2_empty empty Input 2
add_interface_port st_sink2 st_sink2_endofpacket endofpacket Input 1
add_interface_port st_sink2 st_sink2_startofpacket startofpacket Input 1
add_interface_port st_sink2 st_sink2_ready ready Output 1
add_interface_port st_sink2 st_sink2_valid valid Input 1


# 
# connection point st_sink3
# 
add_interface st_sink3 avalon_streaming end
set_interface_property st_sink3 associatedClock clock
set_interface_property st_sink3 associatedReset reset
set_interface_property st_sink3 dataBitsPerSymbol 8
set_interface_property st_sink3 errorDescriptor ""
set_interface_property st_sink3 firstSymbolInHighOrderBits true
set_interface_property st_sink3 maxChannel 0
set_interface_property st_sink3 readyLatency 0
set_interface_property st_sink3 ENABLED true
set_interface_property st_sink3 EXPORT_OF ""
set_interface_property st_sink3 PORT_NAME_MAP ""
set_interface_property st_sink3 CMSIS_SVD_VARIABLES ""
set_interface_property st_sink3 SVD_ADDRESS_GROUP ""

add_interface_port st_sink3 st_sink3_data data Input 16
add_interface_port st_sink3 st_sink3_empty empty Input 2
add_interface_port st_sink3 st_sink3_endofpacket endofpacket Input 1
add_interface_port st_sink3 st_sink3_startofpacket startofpacket Input 1
add_interface_port st_sink3 st_sink3_ready ready Output 1
add_interface_port st_sink3 st_sink3_valid valid Input 1

