# TCL File Generated by Component Editor 16.1
# Mon Aug 04 19:09:05 EST 2025
# DO NOT MODIFY


# 
# vga_sprite_stream "vga_sprite_stream" v1.0
#  2025.08.04.19:09:05
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_sprite_stream
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_sprite_stream
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Private IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_sprite_stream
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_sprite_stream
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fifo.sv SYSTEM_VERILOG PATH ../utils/fifo.sv
add_fileset_file vga_sprite_stream.sv SYSTEM_VERILOG PATH vga_sprite_stream.sv TOP_LEVEL_FILE
add_fileset_file vga_frame_buffer_prefetch.sv SYSTEM_VERILOG PATH vga_frame_buffer_prefetch.sv
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH vga_pkg.sv
add_fileset_file width_narrowing_adapter.sv SYSTEM_VERILOG PATH ../utils/width_narrowing_adapter.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_sprite_stream
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fifo.sv SYSTEM_VERILOG PATH ../utils/fifo.sv
add_fileset_file vga_sprite_stream.sv SYSTEM_VERILOG PATH vga_sprite_stream.sv
add_fileset_file vga_frame_buffer_prefetch.sv SYSTEM_VERILOG PATH vga_frame_buffer_prefetch.sv
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH vga_pkg.sv
add_fileset_file width_narrowing_adapter.sv SYSTEM_VERILOG PATH ../utils/width_narrowing_adapter.sv


# 
# parameters
# 
add_parameter MM_START_ADDRESS INTEGER 67108864
set_parameter_property MM_START_ADDRESS DEFAULT_VALUE 67108864
set_parameter_property MM_START_ADDRESS DISPLAY_NAME MM_START_ADDRESS
set_parameter_property MM_START_ADDRESS TYPE INTEGER
set_parameter_property MM_START_ADDRESS UNITS None
set_parameter_property MM_START_ADDRESS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_START_ADDRESS HDL_PARAMETER true
add_parameter SPRITE_WIDTH INTEGER 48
set_parameter_property SPRITE_WIDTH DEFAULT_VALUE 48
set_parameter_property SPRITE_WIDTH DISPLAY_NAME SPRITE_WIDTH
set_parameter_property SPRITE_WIDTH TYPE INTEGER
set_parameter_property SPRITE_WIDTH UNITS None
set_parameter_property SPRITE_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SPRITE_WIDTH HDL_PARAMETER true
add_parameter SPRITE_HEIGHT INTEGER 48
set_parameter_property SPRITE_HEIGHT DEFAULT_VALUE 48
set_parameter_property SPRITE_HEIGHT DISPLAY_NAME SPRITE_HEIGHT
set_parameter_property SPRITE_HEIGHT TYPE INTEGER
set_parameter_property SPRITE_HEIGHT UNITS None
set_parameter_property SPRITE_HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property SPRITE_HEIGHT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point mm_master_sdram
# 
add_interface mm_master_sdram avalon start
set_interface_property mm_master_sdram addressUnits SYMBOLS
set_interface_property mm_master_sdram associatedClock clock
set_interface_property mm_master_sdram associatedReset reset
set_interface_property mm_master_sdram bitsPerSymbol 8
set_interface_property mm_master_sdram burstOnBurstBoundariesOnly false
set_interface_property mm_master_sdram burstcountUnits WORDS
set_interface_property mm_master_sdram doStreamReads false
set_interface_property mm_master_sdram doStreamWrites false
set_interface_property mm_master_sdram holdTime 0
set_interface_property mm_master_sdram linewrapBursts false
set_interface_property mm_master_sdram maximumPendingReadTransactions 7
set_interface_property mm_master_sdram maximumPendingWriteTransactions 0
set_interface_property mm_master_sdram readLatency 0
set_interface_property mm_master_sdram readWaitTime 1
set_interface_property mm_master_sdram setupTime 0
set_interface_property mm_master_sdram timingUnits Cycles
set_interface_property mm_master_sdram writeWaitTime 0
set_interface_property mm_master_sdram ENABLED true
set_interface_property mm_master_sdram EXPORT_OF ""
set_interface_property mm_master_sdram PORT_NAME_MAP ""
set_interface_property mm_master_sdram CMSIS_SVD_VARIABLES ""
set_interface_property mm_master_sdram SVD_ADDRESS_GROUP ""

add_interface_port mm_master_sdram mm_mem_read read Output 1
add_interface_port mm_master_sdram mm_mem_address address Output 32
add_interface_port mm_master_sdram mm_mem_byteenable byteenable Output 2
add_interface_port mm_master_sdram mm_mem_readdata readdata Input 16
add_interface_port mm_master_sdram mm_mem_waitrequest waitrequest Input 1
add_interface_port mm_master_sdram mm_mem_readdatavalid readdatavalid Input 1


# 
# connection point mm_slave_csr
# 
add_interface mm_slave_csr avalon end
set_interface_property mm_slave_csr addressUnits WORDS
set_interface_property mm_slave_csr associatedClock clock
set_interface_property mm_slave_csr associatedReset reset
set_interface_property mm_slave_csr bitsPerSymbol 8
set_interface_property mm_slave_csr burstOnBurstBoundariesOnly false
set_interface_property mm_slave_csr burstcountUnits WORDS
set_interface_property mm_slave_csr explicitAddressSpan 0
set_interface_property mm_slave_csr holdTime 0
set_interface_property mm_slave_csr linewrapBursts false
set_interface_property mm_slave_csr maximumPendingReadTransactions 0
set_interface_property mm_slave_csr maximumPendingWriteTransactions 0
set_interface_property mm_slave_csr readLatency 0
set_interface_property mm_slave_csr readWaitTime 1
set_interface_property mm_slave_csr setupTime 0
set_interface_property mm_slave_csr timingUnits Cycles
set_interface_property mm_slave_csr writeWaitTime 0
set_interface_property mm_slave_csr ENABLED true
set_interface_property mm_slave_csr EXPORT_OF ""
set_interface_property mm_slave_csr PORT_NAME_MAP ""
set_interface_property mm_slave_csr CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave_csr SVD_ADDRESS_GROUP ""

add_interface_port mm_slave_csr mm_csr_write write Input 1
add_interface_port mm_slave_csr mm_csr_address address Input 4
add_interface_port mm_slave_csr mm_csr_writedata writedata Input 32
add_interface_port mm_slave_csr mm_csr_waitrequest waitrequest Output 1
set_interface_assignment mm_slave_csr embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isPrintableDevice 0


# 
# connection point framebuffer_source
# 
add_interface framebuffer_source avalon_streaming start
set_interface_property framebuffer_source associatedClock clock
set_interface_property framebuffer_source associatedReset reset
set_interface_property framebuffer_source dataBitsPerSymbol 8
set_interface_property framebuffer_source errorDescriptor ""
set_interface_property framebuffer_source firstSymbolInHighOrderBits true
set_interface_property framebuffer_source maxChannel 0
set_interface_property framebuffer_source readyLatency 0
set_interface_property framebuffer_source ENABLED true
set_interface_property framebuffer_source EXPORT_OF ""
set_interface_property framebuffer_source PORT_NAME_MAP ""
set_interface_property framebuffer_source CMSIS_SVD_VARIABLES ""
set_interface_property framebuffer_source SVD_ADDRESS_GROUP ""

add_interface_port framebuffer_source st_endofpacket endofpacket Output 1
add_interface_port framebuffer_source st_startofpacket startofpacket Output 1
add_interface_port framebuffer_source st_data data Output 16
add_interface_port framebuffer_source st_valid valid Output 1
add_interface_port framebuffer_source st_ready ready Input 1
add_interface_port framebuffer_source st_empty empty Output 2

