# TCL File Generated by Component Editor 20.1
# Fri Aug 15 18:58:02 AEST 2025
# DO NOT MODIFY


# 
# vga_display "vga_display" v1.0
#  2025.08.15.18:58:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_display
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_display
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Private IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_display
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_display
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH vga_pkg.sv
add_fileset_file vga_horiz_fsm.sv SYSTEM_VERILOG PATH vga_horiz_fsm.sv
add_fileset_file vga_vert_fsm.sv SYSTEM_VERILOG PATH vga_vert_fsm.sv
add_fileset_file vga_display.sv SYSTEM_VERILOG PATH vga_display.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_display
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_pkg.sv SYSTEM_VERILOG PATH vga_pkg.sv
add_fileset_file vga_horiz_fsm.sv SYSTEM_VERILOG PATH vga_horiz_fsm.sv
add_fileset_file vga_vert_fsm.sv SYSTEM_VERILOG PATH vga_vert_fsm.sv
add_fileset_file vga_display.sv SYSTEM_VERILOG PATH vga_display.sv


# 
# parameters
# 
add_parameter ST_DATA_WIDTH INTEGER 16 ""
set_parameter_property ST_DATA_WIDTH DEFAULT_VALUE 16
set_parameter_property ST_DATA_WIDTH DISPLAY_NAME ST_DATA_WIDTH
set_parameter_property ST_DATA_WIDTH TYPE INTEGER
set_parameter_property ST_DATA_WIDTH UNITS None
set_parameter_property ST_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ST_DATA_WIDTH DESCRIPTION ""
set_parameter_property ST_DATA_WIDTH HDL_PARAMETER true
add_parameter MM_CSR_START_ADDRESS INTEGER 0
set_parameter_property MM_CSR_START_ADDRESS DEFAULT_VALUE 0
set_parameter_property MM_CSR_START_ADDRESS DISPLAY_NAME MM_CSR_START_ADDRESS
set_parameter_property MM_CSR_START_ADDRESS TYPE INTEGER
set_parameter_property MM_CSR_START_ADDRESS UNITS None
set_parameter_property MM_CSR_START_ADDRESS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MM_CSR_START_ADDRESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point framebuffer_sink
# 
add_interface framebuffer_sink avalon_streaming end
set_interface_property framebuffer_sink associatedClock clock
set_interface_property framebuffer_sink associatedReset reset
set_interface_property framebuffer_sink dataBitsPerSymbol 8
set_interface_property framebuffer_sink errorDescriptor ""
set_interface_property framebuffer_sink firstSymbolInHighOrderBits true
set_interface_property framebuffer_sink maxChannel 0
set_interface_property framebuffer_sink readyLatency 0
set_interface_property framebuffer_sink ENABLED true
set_interface_property framebuffer_sink EXPORT_OF ""
set_interface_property framebuffer_sink PORT_NAME_MAP ""
set_interface_property framebuffer_sink CMSIS_SVD_VARIABLES ""
set_interface_property framebuffer_sink SVD_ADDRESS_GROUP ""

add_interface_port framebuffer_sink st_ready ready Output 1
add_interface_port framebuffer_sink st_data data Input ST_DATA_WIDTH
add_interface_port framebuffer_sink st_startofpacket startofpacket Input 1
add_interface_port framebuffer_sink st_endofpacket endofpacket Input 1
add_interface_port framebuffer_sink st_valid valid Input 1


# 
# connection point vga_connector
# 
add_interface vga_connector conduit end
set_interface_property vga_connector associatedClock clock
set_interface_property vga_connector associatedReset reset
set_interface_property vga_connector ENABLED true
set_interface_property vga_connector EXPORT_OF ""
set_interface_property vga_connector PORT_NAME_MAP ""
set_interface_property vga_connector CMSIS_SVD_VARIABLES ""
set_interface_property vga_connector SVD_ADDRESS_GROUP ""

add_interface_port vga_connector vga_hs_out vga_hs Output 1
add_interface_port vga_connector vga_vs_out vga_vs Output 1
add_interface_port vga_connector vga_r vga_r Output 4
add_interface_port vga_connector vga_g vga_g Output 4
add_interface_port vga_connector vga_b vga_b Output 4


# 
# connection point mm_master_csr
# 
add_interface mm_master_csr avalon start
set_interface_property mm_master_csr addressUnits SYMBOLS
set_interface_property mm_master_csr associatedClock clock
set_interface_property mm_master_csr associatedReset reset
set_interface_property mm_master_csr bitsPerSymbol 8
set_interface_property mm_master_csr burstOnBurstBoundariesOnly false
set_interface_property mm_master_csr burstcountUnits WORDS
set_interface_property mm_master_csr doStreamReads false
set_interface_property mm_master_csr doStreamWrites false
set_interface_property mm_master_csr holdTime 0
set_interface_property mm_master_csr linewrapBursts false
set_interface_property mm_master_csr maximumPendingReadTransactions 0
set_interface_property mm_master_csr maximumPendingWriteTransactions 0
set_interface_property mm_master_csr readLatency 0
set_interface_property mm_master_csr readWaitTime 1
set_interface_property mm_master_csr setupTime 0
set_interface_property mm_master_csr timingUnits Cycles
set_interface_property mm_master_csr writeWaitTime 0
set_interface_property mm_master_csr ENABLED true
set_interface_property mm_master_csr EXPORT_OF ""
set_interface_property mm_master_csr PORT_NAME_MAP ""
set_interface_property mm_master_csr CMSIS_SVD_VARIABLES ""
set_interface_property mm_master_csr SVD_ADDRESS_GROUP ""

add_interface_port mm_master_csr mm_csr_write write Output 1
add_interface_port mm_master_csr mm_csr_address address Output 32
add_interface_port mm_master_csr mm_csr_writedata writedata Output 32
add_interface_port mm_master_csr mm_csr_waitrequest waitrequest Input 1

