# TCL File Generated by Component Editor 20.1
# Sun Aug 24 20:27:19 AEST 2025
# DO NOT MODIFY


# 
# seg7_number_display "seg7_number_display" v1.0
#  2025.08.24.20:27:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module seg7_number_display
# 
set_module_property DESCRIPTION ""
set_module_property NAME seg7_number_display
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Private IPs"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME seg7_number_display
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL seg7_number_display
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bin2bcd.sv SYSTEM_VERILOG PATH bin2bcd.sv
add_fileset_file seg7_display.sv SYSTEM_VERILOG PATH seg7_display.sv
add_fileset_file seg7_number_display.sv SYSTEM_VERILOG PATH seg7_number_display.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL seg7_number_display
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file bin2bcd.sv SYSTEM_VERILOG PATH bin2bcd.sv
add_fileset_file seg7_display.sv SYSTEM_VERILOG PATH seg7_display.sv
add_fileset_file seg7_number_display.sv SYSTEM_VERILOG PATH seg7_number_display.sv


# 
# parameters
# 
add_parameter BINARY_DATA_WIDTH INTEGER 32 ""
set_parameter_property BINARY_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property BINARY_DATA_WIDTH DISPLAY_NAME BINARY_DATA_WIDTH
set_parameter_property BINARY_DATA_WIDTH TYPE INTEGER
set_parameter_property BINARY_DATA_WIDTH UNITS None
set_parameter_property BINARY_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BINARY_DATA_WIDTH DESCRIPTION ""
set_parameter_property BINARY_DATA_WIDTH HDL_PARAMETER true
add_parameter BCD_DIGITS INTEGER 6 ""
set_parameter_property BCD_DIGITS DEFAULT_VALUE 6
set_parameter_property BCD_DIGITS DISPLAY_NAME BCD_DIGITS
set_parameter_property BCD_DIGITS TYPE INTEGER
set_parameter_property BCD_DIGITS UNITS None
set_parameter_property BCD_DIGITS ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BCD_DIGITS DESCRIPTION ""
set_parameter_property BCD_DIGITS HDL_PARAMETER true
add_parameter CSR_ADDR_WIDTH INTEGER 4
set_parameter_property CSR_ADDR_WIDTH DEFAULT_VALUE 4
set_parameter_property CSR_ADDR_WIDTH DISPLAY_NAME CSR_ADDR_WIDTH
set_parameter_property CSR_ADDR_WIDTH TYPE INTEGER
set_parameter_property CSR_ADDR_WIDTH UNITS None
set_parameter_property CSR_ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_ADDR_WIDTH HDL_PARAMETER true
add_parameter CSR_DATA_WIDTH INTEGER 32
set_parameter_property CSR_DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property CSR_DATA_WIDTH DISPLAY_NAME CSR_DATA_WIDTH
set_parameter_property CSR_DATA_WIDTH TYPE INTEGER
set_parameter_property CSR_DATA_WIDTH UNITS None
set_parameter_property CSR_DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property CSR_DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point seg7_display
# 
add_interface seg7_display conduit end
set_interface_property seg7_display associatedClock clock
set_interface_property seg7_display associatedReset reset
set_interface_property seg7_display ENABLED true
set_interface_property seg7_display EXPORT_OF ""
set_interface_property seg7_display PORT_NAME_MAP ""
set_interface_property seg7_display CMSIS_SVD_VARIABLES ""
set_interface_property seg7_display SVD_ADDRESS_GROUP ""

add_interface_port seg7_display digits digits Output 48


# 
# connection point mm_slave_csr
# 
add_interface mm_slave_csr avalon end
set_interface_property mm_slave_csr addressUnits WORDS
set_interface_property mm_slave_csr associatedClock clock
set_interface_property mm_slave_csr associatedReset reset
set_interface_property mm_slave_csr bitsPerSymbol 8
set_interface_property mm_slave_csr burstOnBurstBoundariesOnly false
set_interface_property mm_slave_csr burstcountUnits WORDS
set_interface_property mm_slave_csr explicitAddressSpan 0
set_interface_property mm_slave_csr holdTime 0
set_interface_property mm_slave_csr linewrapBursts false
set_interface_property mm_slave_csr maximumPendingReadTransactions 0
set_interface_property mm_slave_csr maximumPendingWriteTransactions 0
set_interface_property mm_slave_csr readLatency 0
set_interface_property mm_slave_csr readWaitTime 1
set_interface_property mm_slave_csr setupTime 0
set_interface_property mm_slave_csr timingUnits Cycles
set_interface_property mm_slave_csr writeWaitTime 0
set_interface_property mm_slave_csr ENABLED true
set_interface_property mm_slave_csr EXPORT_OF ""
set_interface_property mm_slave_csr PORT_NAME_MAP ""
set_interface_property mm_slave_csr CMSIS_SVD_VARIABLES ""
set_interface_property mm_slave_csr SVD_ADDRESS_GROUP ""

add_interface_port mm_slave_csr mm_csr_write write Input 1
add_interface_port mm_slave_csr mm_csr_address address Input CSR_ADDR_WIDTH
add_interface_port mm_slave_csr mm_csr_writedata writedata Input CSR_DATA_WIDTH
add_interface_port mm_slave_csr mm_csr_waitrequest waitrequest Output 1
set_interface_assignment mm_slave_csr embeddedsw.configuration.isFlash 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment mm_slave_csr embeddedsw.configuration.isPrintableDevice 0

