# TCL File Generated by Component Editor 20.1
# Mon Aug 18 19:07:56 AEST 2025
# DO NOT MODIFY


# 
# graphics_instruction "graphics_instruction" v1.0
#  2025.08.18.19:07:56
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module graphics_instruction
# 
set_module_property DESCRIPTION ""
set_module_property NAME graphics_instruction
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME graphics_instruction
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL graphics_instruction
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file graphics_instruction.sv SYSTEM_VERILOG PATH graphics_instruction.sv TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 1
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave nios_clken clk_en Input 1
add_interface_port nios_custom_instruction_slave dataa dataa Input 32
add_interface_port nios_custom_instruction_slave start start Input 1
add_interface_port nios_custom_instruction_slave done done Output 1
add_interface_port nios_custom_instruction_slave nios_clk clk Input 1
add_interface_port nios_custom_instruction_slave nios_reset reset Input 1


# 
# connection point line_op_ctrl
# 
add_interface line_op_ctrl conduit end
set_interface_property line_op_ctrl associatedClock clock
set_interface_property line_op_ctrl associatedReset reset
set_interface_property line_op_ctrl ENABLED true
set_interface_property line_op_ctrl EXPORT_OF ""
set_interface_property line_op_ctrl PORT_NAME_MAP ""
set_interface_property line_op_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property line_op_ctrl SVD_ADDRESS_GROUP ""

add_interface_port line_op_ctrl line_start start Output 1
add_interface_port line_op_ctrl line_done done Input 1
add_interface_port line_op_ctrl line_clken clken Output 1


# 
# connection point rect_fill_op_ctrl
# 
add_interface rect_fill_op_ctrl conduit end
set_interface_property rect_fill_op_ctrl associatedClock clock
set_interface_property rect_fill_op_ctrl associatedReset reset
set_interface_property rect_fill_op_ctrl ENABLED true
set_interface_property rect_fill_op_ctrl EXPORT_OF ""
set_interface_property rect_fill_op_ctrl PORT_NAME_MAP ""
set_interface_property rect_fill_op_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property rect_fill_op_ctrl SVD_ADDRESS_GROUP ""

add_interface_port rect_fill_op_ctrl rect_fill_start start Output 1
add_interface_port rect_fill_op_ctrl rect_fill_done done Input 1
add_interface_port rect_fill_op_ctrl rect_fill_clken clken Output 1


# 
# connection point rect_move_op_ctrl
# 
add_interface rect_move_op_ctrl conduit end
set_interface_property rect_move_op_ctrl associatedClock clock
set_interface_property rect_move_op_ctrl associatedReset reset
set_interface_property rect_move_op_ctrl ENABLED true
set_interface_property rect_move_op_ctrl EXPORT_OF ""
set_interface_property rect_move_op_ctrl PORT_NAME_MAP ""
set_interface_property rect_move_op_ctrl CMSIS_SVD_VARIABLES ""
set_interface_property rect_move_op_ctrl SVD_ADDRESS_GROUP ""

add_interface_port rect_move_op_ctrl rect_move_clken clken Output 1
add_interface_port rect_move_op_ctrl rect_move_start start Output 1
add_interface_port rect_move_op_ctrl rect_move_done done Input 1

